namespace TRLevelControl.Model;

//_S are sprites
//_M are menu items

//_P are pickup items
//_N are nullmeshes (no render/collision)
//_H are helper entities (not placed)
//_U are unused entities
public enum TR1Type : uint
{
    Lara                   = 0,
    LaraPistolAnim_H       = 1,
    LaraShotgunAnim_H      = 2,
    LaraMagnumAnim_H       = 3,
    LaraUziAnimation_H     = 4,
    LaraMiscAnim_H         = 5,
    Doppelganger           = 6,
    Wolf                   = 7,
    Bear                   = 8,
    Bat                    = 9,
    CrocodileLand          = 10,
    CrocodileWater         = 11,
    Lion                   = 12,
    Lioness                = 13,
    Panther                = 14,
    Gorilla                = 15,
    RatLand                = 16,
    RatWater               = 17,
    TRex                   = 18,
    Raptor                 = 19,
    FlyingAtlantean        = 20,
    ShootingAtlantean_N    = 21, // Requires FlyingAtlantean
    NonShootingAtlantean_N = 22, // Requires FlyingAtlantean
    Centaur                = 23,
    Mummy                  = 24, // Qualopec only, Egypt = NonShootingAtlantean_N
    DinoWarrior_U          = 25,
    Fish_U                 = 26,
    Larson                 = 27,
    Pierre                 = 28,
    Skateboard             = 29,
    SkateboardKid          = 30,
    Cowboy                 = 31,
    Kold                   = 32,
    Natla                  = 33,
    Adam                   = 34,
    FallingBlock           = 35,
    SwingingBlade          = 36,
    TeethSpikes            = 37,
    RollingBall            = 38,
    Dart_H                 = 39,
    DartEmitter            = 40,
    LiftingDoor            = 41,
    SlammingDoor           = 42,
    DamoclesSword          = 43,
    ThorHammerHandle       = 44,
    ThorHammerBlock        = 45,
    ThorLightning          = 46,
    Barricade              = 47,
    PushBlock1             = 48,
    PushBlock2             = 49,
    PushBlock3             = 50,
    PushBlock4             = 51,
    MovingBlock            = 52,
    FallingCeiling1        = 53,
    FallingCeiling2        = 54,
    WallSwitch             = 55,
    UnderwaterSwitch       = 56,
    Door1                  = 57,
    Door2                  = 58,
    Door3                  = 59,
    Door4                  = 60,
    Door5                  = 61,
    Door6                  = 62,
    Door7                  = 63,
    Door8                  = 64,
    Trapdoor1              = 65,
    Trapdoor2              = 66,
    Trapdoor3              = 67,
    BridgeFlat             = 68,
    BridgeTilt1            = 69,
    BridgeTilt2            = 70,
    PassportOpen_M_H       = 71,
    Compass_M_H            = 72,
    LaraHomePhoto_M_H      = 73,
    Animating1             = 74,
    Animating2             = 75,
    Animating3             = 76,
    CutsceneActor1         = 77,
    CutsceneActor2         = 78,
    CutsceneActor3         = 79,
    CutsceneActor4         = 80,
    PassportClosed_M_H     = 81,
    Map_M_U                = 82,
    SavegameCrystal_P      = 83,
    Pistols_S_P            = 84,
    Shotgun_S_P            = 85,
    Magnums_S_P            = 86,
    Uzis_S_P               = 87,
    PistolAmmo_S_P         = 88,
    ShotgunAmmo_S_P        = 89,
    MagnumAmmo_S_P         = 90,
    UziAmmo_S_P            = 91,
    Explosive_S_U          = 92,
    SmallMed_S_P           = 93,
    LargeMed_S_P           = 94,
    Sunglasses_M_H         = 95,
    CassettePlayer_M_H     = 96,
    DirectionKeys_M_H      = 97,
    Flashlight_U           = 98,
    Pistols_M_H            = 99,
    Shotgun_M_H            = 100,
    Magnums_M_H            = 101,
    Uzis_M_H               = 102,
    PistolAmmo_M_H         = 103,
    ShotgunAmmo_M_H        = 104,
    MagnumAmmo_M_H         = 105,
    UziAmmo_M_H            = 106,
    Explosive_M_H_U        = 107,
    SmallMed_M_H           = 108,
    LargeMed_M_H           = 109,
    Puzzle1_S_P            = 110,
    Puzzle2_S_P            = 111,
    Puzzle3_S_P            = 112,
    Puzzle4_S_P            = 113,
    Puzzle1_M_H            = 114,
    Puzzle2_M_H            = 115,
    Puzzle3_M_H            = 116,
    Puzzle4_M_H            = 117,
    PuzzleHole1            = 118,
    PuzzleHole2            = 119,
    PuzzleHole3            = 120,
    PuzzleHole4            = 121,
    PuzzleDone1            = 122,
    PuzzleDone2            = 123,
    PuzzleDone3            = 124,
    PuzzleDone4            = 125,
    LeadBar_S_P            = 126,
    LeadBar_M_H            = 127,
    MidasHand_N            = 128,
    Key1_S_P               = 129,
    Key2_S_P               = 130,
    Key3_S_P               = 131,
    Key4_S_P               = 132,
    Key1_M_H               = 133,
    Key2_M_H               = 134,
    Key3_M_H               = 135,
    Key4_M_H               = 136,
    Keyhole1               = 137,
    Keyhole2               = 138,
    Keyhole3               = 139,
    Keyhole4               = 140,
    Quest1_S_P             = 141,
    Quest2_S_P             = 142,
    ScionPiece1_S_P        = 143, // ToQ and Sanctuary - triggers LaraMiscAnim
    ScionPiece2_S_P        = 144, // From Pierre - normal pickup
    ScionPiece3_S_P        = 145, // Great Pyramid - targetable
    ScionPiece4_S_P        = 146, // Atlantis - triggers LaraMiscAnim
    ScionHolder            = 147,
    Quest1_M_H             = 148,
    Quest2_M_H             = 149,
    ScionPiece_M_H         = 150,
    Explosion1_S_H         = 151,
    Explosion2_S_H         = 152,
    WaterRipples1_S_H      = 153,
    WaterRipples2_S_H      = 154,
    Bubbles1_S_H           = 155,
    Bubbles2_S_H           = 156,
    BubbleEmitter_N        = 157,
    Blood1_S_H             = 158,
    Blood2_S_H             = 159,
    DartEffect_S_H         = 160,
    CentaurStatue          = 161,
    NatlasMineShack        = 162,
    AtlanteanEgg           = 163,
    Ricochet_S_H           = 164,
    Sparkles_S_H           = 165,
    Gunflare_H             = 166,
    Dust_S_H               = 167,
    BodyPart_N             = 168,
    CameraTarget_N         = 169,
    WaterfallMist_N        = 170,
    Missile1_H             = 171, // Natla
    Missile2_H             = 172, // Meatball
    Missile3_H             = 173, // Bone
    Missile4_U             = 174,
    Missile5_U             = 175,
    LavaParticles_S_H      = 176,
    LavaEmitter_N          = 177,
    Flame_S_H              = 178,
    FlameEmitter_N         = 179,
    AtlanteanLava          = 180,
    AdamEgg                = 181,
    Motorboat              = 182,
    Earthquake_N           = 183,

    Unused01               = 184,
    Unused02               = 185,
    Unused03               = 186,
    Unused04               = 187,
    Unused05               = 188,
    
    // TR1X
    Skybox_H               = Unused01,
    PickupAid_S_H          = Unused02,
    Glow_S_H               = Unused03,

    LaraPonytail_H_U       = 189,
    FontGraphics_S_H       = 190,

    // Scenery
    Plant0                 = 191,
    Plant1                 = 192,
    Plant2                 = 193,
    Plant3                 = 194,
    Plant4                 = 195,
    Plant5                 = 196,
    Plant6                 = 197,
    Plant7                 = 198,
    Plant8                 = 199,
    Plant9                 = 200,
    Furniture0             = 201,
    Furniture1             = 202,
    Furniture2             = 203,
    Furniture3             = 204,
    Furniture4             = 205,
    Furniture5             = 206,
    Furniture6             = 207,
    Furniture7             = 208,
    Furniture8             = 209,
    Furniture9             = 210,
    Rock0                  = 211,
    Rock1                  = 212,
    Rock2                  = 213,
    Rock3                  = 214,
    Rock4                  = 215,
    Rock5                  = 216,
    Rock6                  = 217,
    Rock7                  = 218,
    Rock8                  = 219,
    Rock9                  = 220,
    Architecture0          = 221,
    Architecture1          = 222,
    Architecture2          = 223,
    Architecture3          = 224,
    Architecture4          = 225,
    Architecture5          = 226,
    Architecture6          = 227,
    Architecture7          = 228,
    Architecture8          = 229,
    Architecture9          = 230,
    Debris0                = 231,
    Debris1                = 232,
    Debris2                = 233,
    Debris3                = 234,
    Debris4                = 235,
    Debris5                = 236,
    Debris6                = 237,
    Debris7                = 238,
    Debris8                = 239,
    Debris9                = 240,
    SceneryBase            = Plant0,

    // Unused models, so repurposed as duplicate puzzle items for importing as secret pickups
    SecretScion_M_H        = 700,
    SecretGoldIdol_M_H     = 701,
    SecretLeadBar_M_H      = 702,
    SecretGoldBar_M_H      = 703,
    SecretAnkh_M_H         = 704,

    SecretScion_S_P        = 800,
    SecretGoldIdol_S_P     = 801,
    SecretLeadBar_S_P      = 802,
    SecretGoldBar_S_P      = 803,
    SecretAnkh_S_P         = 804,

    // Alias entries
    // Egyptian mummies are just NonShootingAtlantean_N, but both depend on FlyingMutant for meshes
    BandagedAtlantean             = 1000,
    MeatyAtlantean                = 1001,
    BandagedFlyer                 = 1002,
    MeatyFlyer                    = 1003,
    CowboyOG                      = 1004,
    CowboyHeadless                = 1005, // From LeoC's Folklorist Diary

    // Extra Lara animations
    LaraMiscAnim_H_General        = 2000,
    LaraMiscAnim_H_Valley         = 2001, // T-Rex death
    LaraMiscAnim_H_Qualopec       = 2002, // Scion pickup
    LaraMiscAnim_H_Midas          = 2003, // Turning to gold
    LaraMiscAnim_H_Sanctuary      = 2004, // Scion pickup (includes level end)
    LaraMiscAnim_H_Atlantis       = 2005, // Scion grab (includes level end)
    LaraMiscAnim_H_Pyramid        = 2006, // Adam death

    // Key item aliases
    CavesKeyItemBase              = 10000,

    VilcabambaKeyItemBase         = 11000,
    Vilcabamba_K1_SilverKey       = 11183,
    Vilcabamba_P1_GoldIdol        = 11143,

    ValleyKeyItemBase             = 12000,
    Valley_P1_CogAbovePool        = 12177,
    Valley_P1_CogBridge           = 12242,
    Valley_P1_CogTemple           = 12241,

    QualopecKeyItemBase           = 13000,

    FollyKeyItemBase              = 14000,
    Folly_K1_NeptuneKey           = 14315,
    Folly_K2_AtlasKey             = 14299,
    Folly_K3_DamoclesKey          = 14290,
    Folly_K4_ThorKey              = 14280,

    ColosseumKeyItemBase          = 15000,
    Colosseum_K1_RustyKey         = 15217,

    MidasKeyItemBase              = 16000,
    Midas_LeadBar_FireRoom        = 16178,
    Midas_LeadBar_SpikeRoom       = 16157,
    Midas_LeadBar_TempleRoof      = 16166,

    CisternKeyItemBase            = 17000,
    Cistern_K1_GoldKey            = 17245,
    Cistern_K2_SilverBehindDoor   = 17208,
    Cistern_K2_SilverBetweenDoors = 17231,
    Cistern_K3_RustyKeyMainRoom   = 17295,
    Cistern_K3_RustyKeyNearPierre = 17143,

    TihocanKeyItemBase            = 18000,
    Tihocan_K1_GoldKeyFlipMap     = 18133,
    Tihocan_K1_GoldKeyPierre      = 18389,
    Tihocan_K2_RustyKeyBoulders   = 18277,
    Tihocan_K2_RustyKeyClangClang = 18267,
    Tihocan_Scion_EndRoom         = 18444,

    KhamoonKeyItemBase            = 19000,
    Khamoon_K1_SapphireKeyEnd     = 19193,
    Khamoon_K1_SapphireKeyStart   = 19217,

    ObeliskKeyItemBase            = 20000,
    Obelisk_K1_SapphireKeyEnd     = 20213,
    Obelisk_K1_SapphireKeyStart   = 20308,
    Obelisk_P1_EyeOfHorus         = 20160,
    Obelisk_P2_Scarab             = 20151,
    Obelisk_P3_SealOfAnubis       = 20152,
    Obelisk_P4_Ankh               = 20163,

    SanctuaryKeyItemBase          = 21000,
    Sanctuary_K1_GoldKey          = 21191,
    Sanctuary_P1_AnkhAfterKey     = 21196,
    Sanctuary_P1_AnkhBehindSphinx = 21100,
    Sanctuary_P2_Scarab           = 21202,

    MinesKeyItemBase              = 22000,
    Mines_K1_RustyKey             = 22137,
    Mines_P1_BoulderFuse          = 22160,
    Mines_P1_ConveyorFuse         = 22183,
    Mines_P1_CowboyFuse           = 22148,
    Mines_P1_CowboyAltFuse        = 22146,
    Mines_P2_PyramidKey           = 22216,

    AtlantisKeyItemBase           = 23000,

    PyramidKeyItemBase            = 24000,

    EgyptKeyItemBase              = 25000,
    Egypt_K1_GoldKey              = 25192,

    CatKeyItemBase                = 26000,
    Cat_K1_OrnateKeyPyramid       = 26146,
    Cat_K1_OrnateKeyCrocPool      = 26196,
    Cat_K1_OrnateKeyTierSouth     = 26192,
    Cat_K1_OrnateKeyTierNorth     = 26303,
    Cat_K1_OrnateKeyCubbySouth    = 26269,
    Cat_K1_OrnateKeyCubbyNorth    = 26365,
    Cat_K1_OrnateKeyCatStatue     = 26206,
}
