namespace TRLevelControl.Model;

public enum TR5FX : short
{
    Turn180           = 0,
    FloorShake        = 1,
    LaraNormal        = 2,
    LaraBubbles       = 3,
    EndLevel          = 4,
    ActivateCamera    = 5,
    ActivateKey       = 6,
    Rumble            = 7,
    SwapCrowbar       = 8,
    TimerField        = 10,
    Explosion         = 11,
    LaraHandsFree     = 12,
    ShootRightGun     = 16,
    ShootLeftGun      = 17,
    HideItem          = 21,
    ShowItem          = 22,
    ResetHair         = 26,
    SetFog            = 28,
    LaraLocation      = 30,
    ResetTest         = 31,
    Footprint         = 32,
    ClearSpiders      = 33,
    LaraLocationPad   = 45,
    KillActiveBaddies = 46,
    TutorialHint1     = 47,
    TutorialHint2     = 48,
    TutorialHint3     = 49,
    TutorialHint4     = 50,
    TutorialHint5     = 51,
    TutorialHint6     = 52,
    TutorialHint7     = 53,
    TutorialHint8     = 54,
    TutorialHint9     = 55,
    TutorialHint10    = 56,
    TutorialHint11    = 57,
    TutorialHint12    = 58,
}
