namespace TRLevelReader.Model.Enums
{
    //_S are sprites
    //_M are menu items

    //_P are pickup items
    //_N are nullmeshes (no render/collision)
    //_H are helper entities (not placed)
    //_U are unused entities
    public enum TREntities
    {
        Lara = 0,
        LaraPistolAnim_H,
        LaraShotgunAnim_H,
        LaraMagnumAnim_H,
        LaraUziAnimation_H,
        LaraMiscAnim_H,
        Doppelganger,
        Wolf,
        Bear,
        Bat,
        CrocodileLand,
        CrocodileWater,
        LionMale,
        LionFemale,
        Panther,
        Gorilla,
        RatLand,
        RatWater,
        TRex,
        Raptor,
        FlyingAtlantean,
        ShootingAtlantean_N,    // Requires FlyingAtlantean
        NonShootingAtlantean_N, // Requires FlyingAtlantean
        Centaur,
        Mummy,
        DinoWarrior_U,
        Fish_U,
        Larson,
        Pierre,
        Skateboard,
        SkateboardKid,
        Cowboy,
        Kold,
        Natla,
        Adam,
        FallingBlock,
        SwingingBlade,
        TeethSpikes,
        RollingBall,
        Dart_H,
        DartEmitter,
        LiftingDoor,
        SlammingDoor,
        DamoclesSword,
        ThorHammerHandle,
        ThorHammerBlock,
        ThorLightning,
        Barricade,
        PushBlock1,
        PushBlock2,
        PushBlock3,
        PushBlock4,
        MovingBlock,
        FallingCeiling,
        DamoclesSword_U, // Duplicate
        WallSwitch,
        UnderwaterSwitch,
        Door1,
        Door2,
        Door3,
        Door4,
        Door5,
        Door6,
        Door7,
        Door8,
        Trapdoor1,
        Trapdoor2,
        BridgeFlat = 68,
        BridgeTilt1,
        BridgeTilt2,
        PassportOpen_M_H,
        Compass_M_H,
        LaraHomePhoto_M_H,
        Animating1,
        Animating2,
        Animating3,
        CutsceneActor1,
        CutsceneActor2,
        CutsceneActor3,
        CutsceneActor4,
        PassportClosed_M_H,
        Map_M_U,
        SavegameCrystal_P,
        Pistols_S_P,
        Shotgun_S_P,
        Magnums_S_P,
        Uzi_S_P,
        PistolAmmo_S_P,
        ShotgunAmmo_S_P,
        MagnumAmmo_S_P,
        UziAmmo_S_P,
        Explosive_S_U,
        SmallMed_S_P,
        LargeMed_S_P,
        Sunglasses_M_H,
        CassettePlayer_M_H,
        DirectionKeys_M_H,
        Flashlight_U,
        Pistols_M_H,
        Shotgun_M_H,
        Magnums_M_H,
        Uzis_M_H,
        PistolAmmo_M_H,
        ShotgunAmmo_M_H,
        MagnumAmmo_M_H,
        UziAmmo_M_H,
        Explosive_M_H_U,
        SmallMed_M_H,
        LargeMed_M_H,
        Puzzle1_S_P,
        Puzzle2_S_P,
        Puzzle3_S_P,
        Puzzle4_S_P,
        Puzzle1_M_H,
        Puzzle2_M_H,
        Puzzle3_M_H,
        Puzzle4_M_H,
        PuzzleHole1,
        PuzzleHole2,
        PuzzleHole3,
        PuzzleHole4,
        PuzzleDone1,
        PuzzleDone2,
        PuzzleDone3,
        PuzzleDone4,
        LeadBar_S_P,
        LeadBar_M_H,
        MidasHand_N,
        Key1_S_P,
        Key2_S_P,
        Key3_S_P,
        Key4_S_P,
        Key1_M_H,
        Key2_M_H,
        Key3_M_H,
        Key4_M_H,
        Keyhole1,
        Keyhole2,
        Keyhole3,
        Keyhole4,
        ScionPiece_P = 143,
        ScionShootable = 145,
        Scion,
        ScionHolder,
        ScionPiece_M_H = 150,
        Explosion_S_H,
        WaterRipples_S_H = 153,
        Bubbles_S_H = 155,
        Blood_S_H = 158,
        Smoke_S_H = 160,
        CentaurStatue,
        NatlasMineShack,
        AtlanteanEgg,
        Ricochet_S_H,
        Sparkles_S_H,
        Gunflare_H,
        CameraTarget_N = 169,
        WaterfallMist_N,
        AtlanteanBullet_H = 172,
        AtlanteanExplosive_H,
        LavaParticles_S_H = 176,
        LavaAirParticleEmitter_N,
        Flame_S_H,
        FlameEmitter_N,
        AtlanteanLava,
        AdamEgg,
        Motorboat,
        Earthquake_N,
        LaraPonytail_H_U = 189,
        FontGraphics_S_H,
        Plant1_S,
        Plant2_S,
        Plant3_S,
        Plant4_S,
        Plant5_S,
        Bag1_S = 200,
        Bag2_S = 204,
        Rock1_S = 212,
        Rock2_S,
        Rock3_S,
        Bag3_S,
        Debris1_S,
        Debris2_S,
        Debris3_S = 231,
        IncaMummy_S = 233,
        Debris4_S = 236,
        Debris5_S,
        Debris6_S,
        Debris7_S
    }
}