using TRLevelControl.Model;

namespace TRLevelControl;

public class TR3MapControl : TRMapControlBase<TR3Type, TR3RAlias>
{
    protected override TR3Type ReadKey(string key)
        => _keyToTypeMap.ContainsKey(key) ? _keyToTypeMap[key] : default;

    protected override string ConvertKey(TR3Type key)
        => _typeToKeyMap[key];

    private static readonly Dictionary<string, TR3Type> _keyToTypeMap = new()
    {
        ["DUMMY"] = default,
        ["AIRLOCK_SWITCH"] = TR3Type.ValveWheelOrPulley,
        ["ANIMATING1"] = TR3Type.Animating1,
        ["ANIMATING2"] = TR3Type.Animating2,
        ["ANIMATING3"] = TR3Type.Animating3,
        ["ANIMATING4"] = TR3Type.Animating4,
        ["ANIMATING5"] = TR3Type.Animating5,
        ["ANIMATING6"] = TR3Type.Animating6,
        ["BIG_ROLLING_BALL"] = TR3Type.GiantBoulder,
        ["BLADE"] = TR3Type.CircularBlade,
        ["BRIDGE_FLAT"] = TR3Type.BridgeFlat,
        ["BRIDGE_TILT1"] = TR3Type.BridgeTilt1,
        ["BRIDGE_TILT2"] = TR3Type.BridgeTilt2,
        ["CEILING_SPIKES"] = TR3Type.SpikyVertWallOrTunnelBorer,
        ["COBRA"] = TR3Type.Cobra,
        ["CROCODILE"] = TR3Type.Croc,
        ["DIVER"] = TR3Type.ScubaSteve,
        ["DOG"] = TR3Type.Dog,
        ["DOOR_TYPE1"] = TR3Type.Door1,
        ["DOOR_TYPE2"] = TR3Type.Door2,
        ["DOOR_TYPE3"] = TR3Type.Door3,
        ["DOOR_TYPE4"] = TR3Type.Door4,
        ["DOOR_TYPE5"] = TR3Type.Door5,
        ["DOOR_TYPE6"] = TR3Type.Door6,
        ["DOOR_TYPE7"] = TR3Type.Door7,
        ["DOOR_TYPE8"] = TR3Type.Door8,
        ["EXTRAFX6"] = TR3Type.ElectricalSwitchBox,
        ["FALLING_BLOCK"] = TR3Type.FallingBlock,
        ["FALLING_CEILING1"] = TR3Type.FallingCeiling,
        ["FAN"] = TR3Type.DamagingAnimating1,
        ["FIREHEAD"] = TR3Type.FireBreathingDragonStatue,
        ["ICICLES"] = TR3Type.DetachableStalactites,
        ["ICON_PICKUP1_ITEM"] = TR3Type.Infada_P,
        ["ICON_PICKUP1_OPTION"] = TR3Type.Infada_M_H,
        ["KEY_HOLE1"] = TR3Type.Keyhole1,
        ["KEY_HOLE2"] = TR3Type.Keyhole2,
        ["KEY_HOLE3"] = TR3Type.Keyhole3,
        ["KEY_HOLE4"] = TR3Type.Keyhole4,
        ["KEY_ITEM1"] = TR3Type.Key1_P,
        ["KEY_ITEM2"] = TR3Type.Key2_P,
        ["KEY_ITEM3"] = TR3Type.Key3_P,
        ["KEY_ITEM4"] = TR3Type.Key4_P,
        ["KEY_OPTION1"] = TR3Type.Key1_M_H,
        ["KEY_OPTION2"] = TR3Type.Key2_M_H,
        ["KEY_OPTION3"] = TR3Type.Key3_M_H,
        ["KEY_OPTION4"] = TR3Type.Key4_M_H,
        ["LIZARD_MAN"] = TR3Type.LizardMan,
        ["LON_MERCENARY1"] = TR3Type.LondonMerc,
        ["MONKEY"] = TR3Type.Monkey,
        ["MOVABLE_BLOCK"] = TR3Type.PushableBlock1,
        ["MOVABLE_BLOCK2"] = TR3Type.PushableBlock2,
        ["MP1"] = TR3Type.MPWithStick,
        ["PASSPORT_OPTION"] = TR3Type.PassportOpening_H,
        ["PENDULUM"] = TR3Type.SwingingThing,
        ["PICKUP_ITEM1"] = TR3Type.Quest1_P,
        ["PICKUP_OPTION1"] = TR3Type.Quest1_M_H,
        ["PLAYER_1"] = TR3Type.CutsceneActor1,
        ["PLAYER_2"] = TR3Type.CutsceneActor2,
        ["PLAYER_3"] = TR3Type.CutsceneActor3,
        ["PLAYER4"] = TR3Type.CutsceneActor4,
        ["PLAYER_4"] = TR3Type.CutsceneActor_4,
        ["PLAYER_5"] = TR3Type.CutsceneActor5,
        ["PLAYER_6"] = TR3Type.CutsceneActor6,
        ["PLAYER_7"] = TR3Type.CutsceneActor7,
        ["PLAYER_8"] = TR3Type.CutsceneActor8,
        ["PLAYER_9"] = TR3Type.CutsceneActor9,
        ["PUNK1"] = TR3Type.Punk,
        ["PUSH_SWITCH"] = TR3Type.PushButtonSwitch,
        ["PUZZLE_DONE1"] = TR3Type.Slot1Full,
        ["PUZZLE_DONE2"] = TR3Type.Slot2Full,
        ["PUZZLE_DONE3"] = TR3Type.Slot3Full,
        ["PUZZLE_DONE4"] = TR3Type.Slot4Full,
        ["PUZZLE_HOLE1"] = TR3Type.Slot1Empty,
        ["PUZZLE_HOLE2"] = TR3Type.Slot2Empty,
        ["PUZZLE_HOLE3"] = TR3Type.Slot3Empty,
        ["PUZZLE_HOLE4"] = TR3Type.Slot4Empty,
        ["PUZZLE_ITEM1"] = TR3Type.Puzzle1_P,
        ["PUZZLE_ITEM2"] = TR3Type.Puzzle2_P,
        ["PUZZLE_ITEM3"] = TR3Type.Puzzle3_P,
        ["PUZZLE_ITEM4"] = TR3Type.Puzzle4_P,
        ["PUZZLE_OPTION1"] = TR3Type.Puzzle1_M_H,
        ["PUZZLE_OPTION2"] = TR3Type.Puzzle2_M_H,
        ["PUZZLE_OPTION3"] = TR3Type.Puzzle3_M_H,
        ["PUZZLE_OPTION4"] = TR3Type.Puzzle4_M_H,
        ["QUADBIKE"] = TR3Type.Quad,
        ["ROLLING_BALL"] = TR3Type.RollingBallOrBarrel,
        ["SECURITY_GUARD"] = TR3Type.LondonGuard,
        ["SMALL_SWITCH"] = TR3Type.SmallWallSwitch,
        ["SMASH_WINDOW"] = TR3Type.DestroyableBoardedUpWindow,
        ["SPIKE_WALL"] = TR3Type.SpikyWall,
        ["SPIKES"] = TR3Type.TeethSpikesOrBarbedWire,
        ["STROBE_LIGHT"] = TR3Type.AlarmLight,
        ["SWING_BOX"] = TR3Type.DamagingAnimating3,
        ["SWITCH_TYPE1"] = TR3Type.WallSwitch,
        ["SWITCH_TYPE2"] = TR3Type.UnderwaterSwitch,
        ["TEETH_TRAP"] = TR3Type.SkeletonTrapOrSlammingDoor,
        ["TIGER"] = TR3Type.Tiger,
        ["TRAIN"] = TR3Type.SubwayTrain,
        ["TRAPDOOR"] = TR3Type.Trapdoor1,
        ["TRAPDOOR2"] = TR3Type.Trapdoor2,
        ["TRIBEAXE"] = TR3Type.TribesmanAxe,
        ["VEHICLE_ANIM"] = TR3Type.LaraVehicleAnimation_H,
        ["VULTURE"] = TR3Type.Vulture,
        ["WHALE"] = TR3Type.KillerWhale,
    };

    private static readonly Dictionary<TR3Type, string> _typeToKeyMap;

    static TR3MapControl()
    {
        _typeToKeyMap = _keyToTypeMap.ToDictionary(e => e.Value, e => e.Key);
    }
}
