namespace TRLevelControl.Model;

public enum TR4FX : short
{
    Turn180           = 0,
    FloorShake        = 1,
    LaraNormal        = 2,
    LaraBubbles       = 3,
    EndLevel          = 4,
    ActivateCamera    = 5,
    ActivateKey       = 6,
    Rumble            = 7,
    SwapCrowbar       = 8,
    TimerField        = 10,
    Explosion         = 11,
    LaraHandsFree     = 12,
    DrawRightGun      = 14,
    DrawLeftGun       = 15,
    ShootRightGun     = 16,
    ShootLeftGun      = 17,
    MeshSwap1         = 18,
    MeshSwap2         = 19,
    MeshSwap3         = 20,
    HideItem          = 21,
    ShowItem          = 22,
    ResetHair         = 26,
    SetFog            = 28,
    GhostTrap         = 29,
    LaraLocation      = 30,
    ClearScarabs      = 31,
    Footprint         = 32,
    PourSwapOn        = 43,
    PourSwapOff       = 44,
    LaraLocationPad   = 45,
    KillActiveBaddies = 46,
}
