<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningLevel>4</WarningLevel>
    <OutputType>Exe</OutputType>
    <SelfContained>false</SelfContained>
    <Copyright>Copyright © Tomb Raider Community 2023</Copyright>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TombIO\RectanglePacker\RectanglePacker\RectanglePacker.csproj" />
    <ProjectReference Include="..\TombIO\TRDataControl\TRDataControl.csproj" />
    <ProjectReference Include="..\TombIO\TRImageControl\TRImageControl.csproj" />
    <ProjectReference Include="..\TombIO\TRLevelControl\TRLevelControl.csproj" />
    <ProjectReference Include="..\TRRandomizerCore\TRRandomizerCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\TileTemplate.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <PropertyGroup>
    <NoWarn>IDE0130</NoWarn>
  </PropertyGroup>
</Project>
