namespace TRLevelControl.Model;

public enum TR2FX : short
{
    Turn180          = 0,
    FloorShake       = 1,
    LaraNormal       = 2,
    LaraBubbles      = 3,
    EndLevel         = 4,
    Flood            = 5,
    Chandelier       = 6,
    Rumble           = 7,
    Pistons          = 8,
    Curtains         = 9,
    SetChange        = 10,
    Explosion        = 11,
    LaraHandsFree    = 12,
    FlipMap          = 13,
    DrawRightGun     = 14,
    DrawLeftGun      = 15,
    MeshSwap1        = 18,
    MeshSwap2        = 19,
    MeshSwap3        = 20,
    HideItem         = 21,
    ShowItem         = 22,
    DynamicLightsOn  = 23,
    DynamicLightsOff = 24,
    Statue           = 25,
    ResetHair        = 26,
    Boiler           = 27,
    AssaultReset     = 28,
    AssaultStop      = 29,
    AssaultStart     = 30,
    AssaultEnd       = 31,
}
