namespace TRRandomizerCore.Globalisation;

public enum TRStringKey
{
    HEADING_GAME_OVER,
    HEADING_INVENTORY,
    HEADING_ITEMS,
    HEADING_OPTION,
    
    INV_ITEM_COMPASS,
    INV_ITEM_CONTROLS,
    INV_ITEM_DETAILS,
    INV_ITEM_GAME,
    INV_ITEM_SOUND,
    INV_ITEM_LARAS_HOME,

    INV_ITEM_MEDI,
    INV_ITEM_BIG_MEDI,
    INV_ITEM_FLARES,    

    INV_ITEM_PISTOLS,
    INV_ITEM_PISTOL_AMMO,
    INV_ITEM_SHOTGUN,
    INV_ITEM_SHOTGUN_AMMO,
    INV_ITEM_MAGNUM,
    INV_ITEM_MAGNUM_AMMO,
    INV_ITEM_AUTOS,
    INV_ITEM_AUTO_AMMO,
    INV_ITEM_DEAGLE,
    INV_ITEM_DEAGLE_AMMO,
    INV_ITEM_UZI,
    INV_ITEM_UZI_AMMO,
    INV_ITEM_HARPOON,
    INV_ITEM_HARPOON_AMMO,
    INV_ITEM_M16,
    INV_ITEM_M16_AMMO,
    INV_ITEM_GRENADE_LAUNCHER,
    INV_ITEM_GRENADE_AMMO,
    INV_ITEM_ROCKET_LAUNCHER,
    INV_ITEM_ROCKETS,

    INV_ITEM_LEADBAR,
    INV_ITEM_SCION,

    MISC_EMPTY_SLOT_FMT,

    INV_GLOBE_LONDON,
    INV_GLOBE_NEVADA,
    INV_GLOBE_SOUTH_PACIFIC,
    INV_GLOBE_ANTARCTICA,
}
