namespace TRLevelControl.Model;

public enum TR3FX : short
{
    Turn180          = 0,
    FloorShake       = 1,
    LaraNormal       = 2,
    LaraBubbles      = 3,
    EndLevel         = 4,
    Flood            = 5,
    Rumble           = 7,
    Explosion        = 11,
    LaraHandsFree    = 12,
    FlipMap          = 13,
    DrawRightGun     = 14,
    DrawLeftGun      = 15,
    ShootRightGun    = 16,
    ShootLeftGun     = 17,
    MeshSwap1        = 18,
    MeshSwap2        = 19,
    MeshSwap3        = 20,
    HideItem         = 21,
    ShowItem         = 22,
    DynamicLightsOn  = 23,
    DynamicLightsOff = 24,
    ResetHair        = 26,
    AssaultReset     = 28,
    AssaultStart     = 30,
    AssaultEnd       = 31,
    Footprint        = 32,
    AssaultPenalty8  = 33,
    RacetrackStart   = 34,
    RacetrackReset   = 35,
    RacetrackEnd     = 36,
    AssaultPenalty30 = 37,
    GymHint1         = 38,
    GymHint2         = 39,
    GymHint3         = 40,
    GymHint4         = 41,
    GymHint5         = 42,
    GymHint6         = 43,
    GymHint7         = 44,
    GymHint8         = 45,
    GymHint9         = 46,
    GymHint10        = 47,
    GymHint11        = 48,
    GymHint12        = 49,
    GymHint13        = 50,
    GymHint14        = 51,
    GymHint15        = 52,
    GymHint16        = 53,
    GymHint17        = 54,
    GymHint18        = 55,
    GymHint19        = 56,
    GymHintReset     = 57,
}
