name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:          
  buildx64:
    name: Build x64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'
          
      - name: Build the solution
        run: |
          dotnet restore
          dotnet test --filter TestCategory!=OriginalIO
          dotnet publish TRRandomizerView -c Release -a x64 --property:PublishDir=build --self-contained false
          
      - name: Package the build
        run: |
          cd TRRandomizerView/build
          dir
          Compress-Archive -Path (Get-ChildItem -Exclude *.pdb) -DestinationPath TRRando-x64.zip
          
      - name: Upload the package
        uses: actions/upload-artifact@v4
        with:
          name: TRRando-x64
          path: TRRandomizerView/build/TRRando-x64.zip
